### ISSUE TITLE
Base64 Decoder issue

### ISSUE THREAD

**Issue by daryabraz** [engswee/equalize-cpi-converter#3]
Hello engswee!

Thank you for the developing such a good cpi converter, it is very easy to use. 
But I faced some issues when working with it. 
Maybe it can be considered even as an enhancement idea.
According to my integration flow I receive a message with Base64 encoded zip file. It was unpacked correctly by your converter but this archive contains several csv files, and only ONE is parsed. And I need all the files to be parsed, as they contain necessary information.
I'm not a developer so I didn't manage to solve it by myself, that's why I'm writing here.

Thanks!

**Comment by engswee** [comment]
Hi daryabraz

Thanks for logging this idea. After further thought on this, I don't think there is a generic way to handle zip files with more than 1 file. There are more questions than answers, e.g. do the files have the same format, do you combine them and how, do you separate them into attachments, how do you process the attachments, etc, etc.

As such, I believe such scenarios should be handled specifically for each integration requirement rather than generically by this converter.

**Comment by daryabraz** [comment]
Hi engswee,

Thank you very much for the reply.
