### ISSUE TITLE
XML2JSON Converter when there are two xml nodes with same name but one is array

### ISSUE THREAD

**Issue by baroni2019** [engswee/equalize-cpi-converter#5]
Hi Eng Swee Yeoh. I've got an use case where a XML to be converted to JSON has two XML nodes with same name, one should be array and the other not. Given that I am not able to use arrayFieldList as it would change the two nodes to array in JSON. So I would like to suggest using XPATH instead of NomeName in the arrayFieldList parameter, so it would be possible to define only one Node to be JSON array and other not. Example below regarding of _"customFields"_:

**XML:**
```
<test>
  <customFields>
     <fields>123</fields>
     <fields>456</fields>
   </customFields>
   <customer>
      <customFields>abc<customFields>
      <customFields>def<customFields>
   </customer>

```

**Desired JSON:**
```
{
   "test" : {
      "customFields" : {
         "fields": [ "123", "456" ]
      },
      "customer": {
         "customFields": [ "abc", "def" ]
      }
   }
}
```

Kind Regards.

**Pedro Baroni**

**Comment by baroni2019** [comment]
Hi Swee, thanks for your reply.

Actually I do have the situation below as well, where wouldn't work based on the occurrence:

XML:

```
<test>
  <customFields>
     <fields>123</fields>
     <fields>456</fields>
   </customFields>
   <customer>
      <customFields>abc<customFields>
   </customer>

```
Desired JSON:

```
{
   "test" : {
      "customFields" : {
         "fields": [ "123", "456" ]
      },
      "customer": {
         "customFields": [ "abc" ]
      }
   }
}
```

**Comment by engswee** [comment]
Hi Pedro

I have released a new version 2.2.0 whereby the JSON processing has been switched to using Groovy's built-in JSON capability. Alongside that, I have added new parameter **arrayGPathList** to cater for your scenario. The parameter works based on GPath of the target JSON structure, instead of XPath of the source XML structure.

For your case, you can configure it like:  _arrayGPathList = test.customer.customFields_
You can refer to the test case in the following Spock specification too
https://github.com/engswee/equalize-cpi-converter/blob/master/src/test/groovy/com/equalize/converter/core/XML2JSONConverterSpec.groovy

Give it a try and let me know how it goes.

**Comment by baroni2019** [comment]
Hi,

Working perfectly, thank you.
My actual scenario is Integration between SAP ECC and DocuSign (Envelopes) via SAP CPI.
SAP ECC side is ABAP Proxy (totally XML).
DocuSign REST APIs using JSON.
In POST Envelope data model there are about 4.000 (yes, four thousand) fields. With some repetitive fieldNames in different formats (p.e. String and Array). Reference: ([DocuSign Envelope Creation REST API](https://developers.docusign.com/esign-rest-api/reference/Envelopes/Envelopes/create))
This brand new "arrayGPathList" helped me a lot and solved the problem quite straightforward.
Look forward to seeing SAP Blog updates.

Many many thanks.

Pedro Baroni

**Comment by engswee** [comment]
Great to hear that it is working now. The reference blog has also been updated. I'll close this issue.
