### ISSUE TITLE
PlaintoXML issue with field separator

### ISSUE THREAD

**Issue by NittyVeer** [engswee/equalize-cpi-converter#7]
Hi Engswee,

I tried to convert a tab delimited file to xml with format conversion bean. Can you guide me how to define tab as field separator in exchange properties.  I used multiple options and nothing seems to work.

attaching iflow, input and output here
[test.txt](https://github.com/engswee/equalize-cpi-converter/files/5682577/test.txt)
[IF_COVANCE_to_S4HANA_IntercompanySTO.zip](https://github.com/engswee/equalize-cpi-converter/files/5682579/IF_COVANCE_to_S4HANA_IntercompanySTO.zip)
[EndEvent_2 (1).zip](https://github.com/engswee/equalize-cpi-converter/files/5682580/EndEvent_2.1.zip)

Thanks,
Nithya

**Comment by engswee** [comment]
Hi Nithya

The issue is with the single quotation marks enclosing characters used in the field separator field.
Somehow the SAP Community Portal renders the "straight" quotation marks into slanted quotation marks.
So **'0x09'** is displayed as **‘0x09’** which is incorrect.

Once I changed it to '0x09' in the IFlow's properties, it is working fine.

Also, from your record structure, I don't think _CovanceMaterialNumber_ field will have unique values that allows it to be used as a key field. Since you are using _genericRecordType_, the parameters _Record.keyFieldValue_ and _keyFieldName_ are not required.

Attached is an updated version of the IFlow with the parameters corrected.

[IF_COVANCE_to_S4HANA_IntercompanySTO (1).zip](https://github.com/engswee/equalize-cpi-converter/files/5684619/IF_COVANCE_to_S4HANA_IntercompanySTO.1.zip)

If you test with the input file, the output XML will be generated correctly as shown below.
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/7220623/102013122-64093300-3d4e-11eb-96bb-0cb9b81c8ac7.png">
